name: xpx_chain_sdk_examples
version: 0.0.1
description: 'The ProximaX Sirius Chain Dart SDK examples.'
author: 'Eleazar Garrido <eleazar.garrido@proximax.io>'
homepage: https://www.proximax.io

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  xpx_crypto: '^0.0.1'
  xpx_chain_sdk: '^0.0.3+4'

dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
